name: Build-Windows-Installer

on:
  push:
    branches: [ "main" ]     # 也可改成 release/* 等
  workflow_dispatch:         # 允许手动触发

env:
  APP_NAME: Vortex
  APP_VERSION: 1.0.0         # 可写死，也可读取 pom.xml
  MAIN_JAR: Vortex-1.0.0.jar
  MAIN_CLASS: tech.mineyyming.vortex.Main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Liberica 21（full = 自带 JavaFX + jpackage）
      - name: Set up Liberica JDK 21-full
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: '21'
          architecture: x64
          cache: maven

      # 3. Maven Build（产生 fat-jar）
      - name: Build with Maven
        run: mvn -B clean package

      # 4. jpackage 生成 app-image（绿色版）
      - name: jpackage – create app-image
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build\app
          jpackage `
            --name "${{ env.APP_NAME }}" `
            --input target `
            --main-jar "${{ env.MAIN_JAR }}" `
            --main-class "${{ env.MAIN_CLASS }}" `
            --type app-image `
            --dest build\app `
            --icon src\main\resources\images\app_icon.png `
            --app-version "${{ env.APP_VERSION }}" `
            --add-modules javafx.controls,javafx.fxml

      # 5. 【替换步骤】使用 Minionguyjpro/Inno-Setup-Action 编译安装包
      - name: Compile Installer with Inno Setup Action
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          # 指定你的 .iss 文件路径
          path: setup.iss
          # 关键：通过 options 参数把动态变量传给 Inno Setup
          options: /DAppName="${{ env.APP_NAME }}" /DAppVersion="${{ env.APP_VERSION }}"

      # 7. 上传产物
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Vortex-installer
          path: |
            Output\Vortex-Setup.exe
